name: Build on push

on:
  push:
    branches: [main]
    tags: ['*']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:


  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Repo checkout
        with:
          persist-credentials: true
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/hyperk/hk-meta-externals:latest
      - name: Push the Docker image
        run: docker push ghcr.io/hyperk/hk-meta-externals:latest
